---
- name: Download selenium on 'master' if we don't have it
  connection: local
  sudo: False
  get_url: url={{download_url}}  dest={{cur_dir}}/{{jar_file}} force=no

- name: Verify integrity of downloaded file
  connection: local
  sudo: False
  command: unzip -qt {{cur_dir}}/{{jar_file}}

- name: Copy selenium into place
  copy: src={{jar_file}}  dest={{ selenium_dir }}/selenium-server.jar owner=root group=root mode=644

- name: Install Config
  template: src=defaults.j2 dest=/etc/default/se_{{sel_role}} owner=root group=root mode=644
  tags: ['config']
  notify: selenium_reload

- name: Install init script
  template: src=debian_init.j2 dest=/etc/init.d/se_{{sel_role}} owner=root group=root mode=755
  tags: ['config']
  notify: selenium_started

- name: Install browser
  apt: name={{item}}
  when: sel_role != 'hub'
  with_items:
    - xvfb
    - firefox
