---
- name: Download selenium on 'master' if we don't have it
  connection: local
  sudo: False
  get_url: url={{download_url}}  dest={{cur_dir}}/{{jar_file}} force=no

- name: Copy selenium into place
  copy: src={{jar_file}}  dest=/usr/local/lib/{{jar_file}} owner=root group=root mode=644

- name: Install Config
  template: src=defaults.j2 dest=/etc/default/selenium_{{sel_role}} owner=root group=root mode=644
  tags: ['config']
  notify: selenium_reload

- name: Install init script
  template: src=init.j2 dest=/etc/init.d/selenium_{{sel_role}} owner=root group=root mode=755
  tags: ['config']
  notify: selenium_started

- name: Install browser
  apt: name={{item}}
  when: sel_role != 'hub'
  with_items:
    - xvfb
    - firefox
