
---
- name: selenium_started
  service: name=se_{{sel_role}} state=started enabled=yes

- name: selenium_reload
  service: name=se_{{sel_role}} state=reloaded

- name: selenium_restarted
  service: name=se_{{sel_role}} state=restarted
